const config = require("./makeRatingFile")
const makeRatingFile  = require("./rating-file")
const updateRating = require("./calculations")
const createRating = require("./calculations")
module.exports(config, makeRatingFile, updateRating, createRating)